version: '3.8'

services:
  bot:
    build: ./tg_bot
    depends_on:
      - app
    environment:
      - BOT_TOKEN=7101161750:AAEMLeS5_v3DDTZ7rwkoZrOt1z7Zw5Op5tM

  app:
    build: ./app
    ports:
      - "8000:8000"
    depends_on:
      db:
          condition: service_healthy
    environment:
      - DB_NAME=example
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=example
      - DB_PASS=example
      - JWT_SECRET=812659050808fd763749156b9b403c46a2338f082b4cc1316d3b0ac8794937aa
      - JWT_ACCESS_TOKEN_TIME=10000
      - JWT_ALGORITHM=HS256

  db:
    image: postgres
    environment:
        - POSTGRES_DB=example
        - POSTGRES_USER=example
        - POSTGRES_PASSWORD=example
    ports:
        - "5433:5432"
    healthcheck:
        test: [ "CMD-SHELL", "pg_isready -U example" ]
        interval: 5s
        timeout: 10s
        retries: 5
